---
execute:               # Default settings for code blocks
  warning: false       # Do not print warnings
  message: false       # Do not print messages
  size: "scriptsize"   # Set code size to script size

format:
  pdf:        # Specify .pdf formatting options 
    documentclass: article     # Document Class
    number-sections: true      # Number Sections
    reference-section-title: "References" # Title for reference section
    code-line-numbers: true    # Line numbers printed in code
    cap-location: top          # Captions at the top of tables 
    geometry:
      - top=0.75in
      - left=0.75in
      - bottom=0.75in
      - right=0.75in
format-links: [pdf]
---
```{r}
#| echo: false

default_chunk_hook  <- knitr::knit_hooks$get("chunk")

latex_font_size <- c("Huge", "huge", "LARGE", "Large", 
                     "large", "normalsize", "small", 
                     "footnotesize", "scriptsize", "tiny")

knitr::knit_hooks$set(chunk = function(x, options) {
  x <- default_chunk_hook(x, options)
  if(options$size %in% latex_font_size) {
    paste0("\n \\", options$size, "\n\n", 
      x, 
      "\n\n \\normalsize"
    )
  } else {
    x
  }
})

```

```{r}
#| label: load-packages
#| include: false
library(tidyverse)
```

<!-- Code For Building Menu Here -->
```{r}
#| include: false
breakfasts <- c("website/BerryMelonSmoothie.html",
                "website/BiscuitsAndGravy.html",
                "website/BreakfastCheesecake.html",
                "website/BreakfastMuffins.html",
                "website/ChiaParfait.html",
                "website/GardenTomatoQuiche.html",
                "website/OvernightOats.html",
                "website/PumpkinToast.html",
                "website/TropicalSmoothie.html")
dinner <- c("website/AfricanPeanutSoup.html",
            "website/Alfredo.html",
            "website/ArugulaPasta.html",
            "website/AutumnGrainBowl.html",
            "website/BakedZiti.html",
            "website/BBQChili.html",
            "website/Bibimbap.html",
            "website/BLTSalad.html",
            "website/Burgers.html",
            "website/CapreseSandwiches.html",
            "website/EggplantParmesan.html",
            "website/Enchiladas.html",
            "website/FloridaRolls.html",
            "website/KimchiGrilledCheese.html",
            "website/Lasagna.html",
            "website/LatinBowl.html",
            "website/Meatloaf.html",
            "website/PadThai.html",
            "website/PastaAndPeas.html",
            "website/Pizza.html",
            "website/RedWineRagu.html",
            "website/SalmonChowder.html",
            "website/Shakshuka.html")

# SOLUTION
library("rvest")

# randomly select our meals and store them all in one vector:
selected.dinners = sample(dinner, 3)
selected.breakfast = sample(breakfasts, 1)

all.meals = c(selected_dinners, selected_breakfast)

for(file in all.meals){
  recipe.item = read_html(file) # read the recipe in
  
  # get title
  title.text = html_element(recipe.item, "title") # find the title (element type
                                                  #was found by opening developer tools for random recipe)
  html_text = (title.text) # retrieves the title
  
  # get image
  image.element = html_element(recipe.item,".img-fluid")
  (src <- html_attr(image.element, "src"))
  (image.url = paste("website/",src, sep = ""))

  # get ingredients
  ingredients.section = html_element(recipe.item,"#ingredients")
  ingredients = html_elements(ingredients.section,"li")

  # get instructions
  instructions.section = html_element(recipe.item,"#instructions")
  instructions = html_elements(instructions.section,"li")
  

}



```



# Ingredients

\newpage

# Recipe One

\newpage

# Recipe Two

\newpage

# Recipe Three

\newpage

# Breakfast Recipe
